language: python
python:
  - 3.8

env:
  global:
    - secure: g+RH5nPJG+umCUJsBSuB7lF9pQP0cfq/lthmzZVVpyEEtv37ESz/2WTsuMYESBAUoKNwvO6mvq6zo1mdkdaWlMLDD39XY7l/Xil2KHzNm4eK64xhC1kpL11pvzYUebQIzO2K70mJuUU2yeFiByob9BtW34Age0w9uFwSC3PLuMofQvv+k7tbYBWXwStyOHzB13pWoGUo20S3K8FMGsbzctOTDk4W6j1G+g0GK7t4Q112yFgahtVl1zQXVoLSVlV8naiZZG1jR9czrBwAZg54qR02vgc4sUv/M9nG6MSBfQtq7WLLKvT47UxnbC/oMmA9CmrIf4Y/ppbJ1KSpF1H28NaTnTR0ij2EbPLNtN81GrHllN2LC40HQcl90+mknKACru1ekw49mEGxFWShCXUmJl5K9KkyGOviXx0u1nn8PVHVgwgetLbjlz5J/ssVZWsIsSqHdt+HcUyAXueaY0W+yy7rsYE1H50JVIf3tYpapbIF8HJe1krTCOi1KDJfsZRcXsvLPbeczxnopMM6Z061Z9kcNFevv0BCG881TjNpubG6axTNF6o/9mp1wBeOybEKDNN98jGm0IRD3PRGMJnX9FhOqznDmYSHnjOeahFx4hzwHmRFgEH4pHWvn4+b122vn7O+Ju7uhdhXjyHuWls6qLn+ck4rSVgUfx3eIUv9ETc=

install:
  - make install

script:
  - make

before_install:
  - sudo apt-get install -y graphviz
  - curl -F "period=5000" -F "color=#AB00FF" "https://api.bi-beacon.com/v1/${BI_BEACON_CHANNELID}/"

before_script:
  - curl -F "period=5000" -F "color=#0000FF" "https://api.bi-beacon.com/v1/${BI_BEACON_CHANNELID}/"

after_success:
  - ./dist/publish-artifacts.sh
  - curl -F "color=#00FF00" "https://api.bi-beacon.com/v1/${BI_BEACON_CHANNELID}/"

after_failure:
  - curl -F "color=#FF0000" "https://api.bi-beacon.com/v1/${BI_BEACON_CHANNELID}/"
